/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-21 05:00:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.paikdabang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import com.project.vo.*;
import java.util.*;

public final class orderResources_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.project.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>주문 재고요청</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/orderResources.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){//수량 증가\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".plus\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar quantity = $(this).parent().find(\"input#quantity\").val(); // $(\"#quantity\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar price = $(this).parent().find(\"input#gagyuk\").val(); //상품가격(alert)\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (quantity < 10) {\r\n");
      out.write("\t\t\t\tquantity++;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).parent().find(\"input#quantity\").val(quantity);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar newqty = $(this).parent().find(\"input#quantity\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).parent().parent().parent().find(\"td span\").text(newqty * price + \"원\");\r\n");
      out.write("\t\t\t\t\t\t\t\t//alert(newqty*price);// 이 가격으로 최종가격 설정해야함.\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//10개까지 구매 가능하다고 띄움\r\n");
      out.write("\t\t\tif (quantity == 10) {\r\n");
      out.write("\t\t\t\t$(this).parent().parent().find(\"div span\").text(\"10개까지 구매 가능합니다\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t  });\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//수량 감소\r\n");
      out.write("\t\t\t\t$(\".minus\").click(function() {\r\n");
      out.write("\t\t\t\t\tvar quantity = $(this).parent().find(\"input#quantity\").val(); // $(\"#quantity\").val();\r\n");
      out.write("\t\t\t\t\tvar price = $(this).parent().find(\"input#gagyuk\").val(); //상품가격(alert)\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (quantity > 1) { //1이상일 때만 감소 가능\r\n");
      out.write("\t\t\t\t\t\tquantity--;\r\n");
      out.write("\t\t\t\t\t\t$(this).parent().find(\"input#quantity\").val(quantity);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar newqty = $(this).parent().find(\t\"input#quantity\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(this).parent().parent().parent().find(\"td span\").text(newqty * price + \"원\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//10개까지 구매 가능한거 지움\r\n");
      out.write("\t\t\t\t\t$(this).parent().parent().find(\"div span\").text(\"\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".buy\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar quantity = $(this).parent().parent().find(\"input#quantity\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar pnum = $(this).parent().find(\"input#pnum\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar size = $(this).parent().find(\"input#size\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar mid= $(this).parent().find(\"input#mid\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar cost = $(this).parent().find(\"input#cost\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar imgsrc = $(this).parent().find(\"input#imgsrc\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar name = $(this).parent().find(\"input#nameofP\").val();\r\n");
      out.write("\t\t\t\t\t\t\tvar cart_id=$(this).parent().find(\"input#cid\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\talert(\"ProductController?command=purchaseCart&pnum=\"+pnum +\"&quantity=\"+quantity+\"&size=\"+size+ \"&mid=\" +mid +\"&price=\" +cost + \"&img=\"+imgsrc+\"&name=\"+name+\"&cartid=\"+cart_id);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"ProductController?command=purchaseCart&pnum=\"+pnum +\"&quantity=\"+quantity+\"&size=\"+size+ \"&mid=\" +mid +\"&price=\" +cost+ \"&img=\"+imgsrc+\"&name=\"+name+\"&cartid=\"+cart_id;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\timg{\r\n");
      out.write("\t\twidth:250px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	List <ResourcesOrderVO> boardList = (List<ResourcesOrderVO>)(request.getAttribute("list"));
	//int totalRowCount = ((Integer) request.getAttribute("totalRowCount")).intValue();
	//int currentPage = ((Integer) request.getAttribute("page")).intValue();
	//int maxPage = ((Integer) request.getAttribute("maxPage")).intValue();
	//int startPage = ((Integer) request.getAttribute("startPage")).intValue();
	//int endPage = ((Integer) request.getAttribute("endPage")).intValue();

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".quantity-manipulation {\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" tr>{\r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		List<ResourcesOrderVO> orderArr = (List<ResourcesOrderVO>)request.getAttribute("orderlist");
		MemberVO member = (MemberVO)request.getAttribute("ceo");
		
		
		
		
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div style = \"margin-top:50px; text-align:center;\">\r\n");
      out.write("\t<h2>");
      out.print((String)request.getSession().getAttribute("userid") );
      out.write("님 주문</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content\" style= \"margin: 0 auto; margin-top:20px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<table class=\"barsket_list\" id=\"mytable\" style = \"margin:0 auto;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\"></th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">상품</th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">상품 이름</th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">상품 가격</th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">상품 갯수</th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">결제금액</th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">구매</th>\r\n");
      out.write("\t\t\t\t<th class=\"td_h\">삭제</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				for (int i = 0; i < orderArr.size(); i++) {
					ResourcesOrderVO pdt = orderArr.get(i);
					
			
      out.write("\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_b_l\"><input type=\"checkbox\" name=\"check\" value=\"");
      out.print(i);
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_b\"><img id=\"img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/");
      out.print(pdt.getImage());
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_b\">");
      out.print(pdt.getDetailExplain());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"price\" class=\"td_b\">");
      out.print(pdt.getPrice());
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_b_r\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"quantity-manipulation\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"-\" class=\"p_down minus\" /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"quantity\" class=\"qtyqty\" name=\"quantity\" class=\"p\" value=\"");
      out.print(pdt.getQuantity());
      out.write("\" style=\"text-align: center; width: 105px;\" /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"+\" class=\"p_up plus\" /><br /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"size\" value=\"");
      out.print(pdt.getQuantity());
      out.write("\" /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"gagyuk\" class=\"gagyuk\" value=\"");
      out.print(pdt.getPrice());
      out.write("\" /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"sum\" class=\"sum\" value=\"");
      out.print(pdt.getPrice() * pdt.getQuantity());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"quantity-inform\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><span id=\"payment\" class=\"payment\">");
      out.print(pdt.getQuantity() * pdt.getPrice());
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class =\"buy\" name=\"purchase\" value=\"구매\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"pnum\" value=\"");
      out.print(pdt.getIdx());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"size\" value=\"");
      out.print(pdt.getType());
      out.write("\"/><!-- 커피/음료 -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getReceiverId());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getOrderId());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getBrand());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(member.getAddress());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(member.getDetailaddress());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getDetailExplain());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"cost\" value=\"");
      out.print(pdt.getPrice());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getCount());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"imgsrc\" value=\"");
      out.print(pdt.getImage());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"nameofP\" value=\"");
      out.print(pdt.getLocation());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getMenu());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getQuantity());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getTemp());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"mid\" value=\"");
      out.print(pdt.getTotalprice());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"cid\" value=\"");
      out.print(pdt.getDate());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" name=\"eliminate\" value=\"삭제\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dabang/deletecart?idx=");
      out.print(pdt.getIdx());
      out.write("' \" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
