/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-02 16:14:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.paikdabang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.project.vo.ProductVO;
import com.project.vo.SurveyVO;
import java.text.DecimalFormat;
import com.project.vo.*;

public final class chart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./header.jsp", Long.valueOf(1604327586714L));
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./footer.jsp", Long.valueOf(1603122796000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.project.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.vo.SurveyVO");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("com.project.vo.ProductVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.8.0\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/itemlist.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$(\"#selectBox\").change(function() {\r\n");
      out.write("\t\tvar num = $(this).val();\r\n");
      out.write("\t\tif(num==(\"매출현황\")){\r\n");
      out.write("\t\tlocation.href=\"saleschart.do?franchisekey=");
      out.print(request.getParameter("franchisekey"));
      out.write("\"}\r\n");
      out.write("\t\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

List<SurveyVO> list = (List<SurveyVO>)request.getAttribute("info"); 
List<SurveyVO> list1 = (List<SurveyVO>)request.getAttribute("paikaverage"); 
System.out.println(list1.toString());

int flavor = 0;
int delivery = 0;
int service = 0;
int count=0;

for(int i=0;i<list1.size();i++){
		flavor += list1.get(i).getFlavor();
		delivery += list1.get(i).getDelivery();
		service += list1.get(i).getService();
		count += list1.get(i).getOrdercount();
} 
	flavor = (int)flavor/count;
	delivery = (int)delivery/count;
	service = (int)service/count;
	
int franflavor =  (list.get(0).getFlavor())/(list.get(0).getOrdercount());
int frandelivery = (list.get(0).getDelivery())/(list.get(0).getOrdercount());
int franservice = (list.get(0).getService())/(list.get(0).getOrdercount());

      out.write("\r\n");
      out.write("<header class = \"header\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/header.css\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	String franchiseid = null;
	String franchisekey = (String) session.getAttribute("franchisekey");
	MemberVO member = null;
	String selectmenu = null;
	String myfkKey = null;
	String mydefaultTier = null;
	
try {
	franchiseid = (String) session.getAttribute("franchiseid");
	selectmenu = (String) request.getAttribute("menu");
	member = (MemberVO) session.getAttribute("loginMember");
	myfkKey = member.getFranchisekey();
	mydefaultTier = member.getTier();
} catch (Exception e) {
	franchiseid = "customer";
	member = new MemberVO();
	member.setIdx(0);
	member.setId("none");
	myfkKey = "a";
	mydefaultTier = "customer";
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar\"\r\n");
      out.write("\t\tstyle=\"display: inline-flex; margin-bottom: 40px; padding: 28px 0px 0px;\">\r\n");
      out.write("\t\t<a class=\"logo\"\r\n");
      out.write("\t\t\tstyle=\"margin-right: 100px; width: 150px; margin-left: 40px;\"> <img\r\n");
      out.write("\t\t\tsrc=\"http://www.paikdabang.com/wp-content/themes/paikdabang/assets/images/logo.png\"\r\n");
      out.write("\t\t\talt=\"빽다방\" style=\"width: 149px;\" />\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"main-menu\">\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/menu.do?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchiseid);
      out.write("\">메뉴</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul style=\"z-index: 1; display: inline-grid; list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/coffee?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchiseid);
      out.write("\">커피</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/dessert?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchiseid);
      out.write("\">아이스크림/디저트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/beverage?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchiseid);
      out.write("\">음료</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/drink?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchiseid);
      out.write("\">빽스치노</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a href=\"\">소식</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul style=\"z-index: 1; display: inline-grid; list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">우수 친절매장</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a href=\"\">매장안내</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				if (franchisekey.equals(myfkKey)) {
				//System.out.println("사장님 들어옴...");
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/resources/order?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">재고주문</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/resources/chart?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">지점평가\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				} else if ("customer".equals(mydefaultTier)) {
			System.out.println("일반소비자");
			}
			
      out.write("\r\n");
      out.write("\t\t\t");
 if(member != null) {
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/basket?id=");
      out.print(member.getId());
      out.write("\">장바구니</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} else if(member == null) {
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/basket\">장바구니</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sub_section menu_wrap\">\r\n");
      out.write("\t<div class=\"container\" style=\"height: 500px\">\r\n");
      out.write("\t\t<div style=\"width:600px; height: 500px; float: left\">\r\n");
      out.write("\t\t    <canvas id=\"myChart\"></canvas>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("// 우선 컨텍스트를 가져옵니다. \r\n");
      out.write("var ctx = document.getElementById(\"myChart\").getContext('2d');\r\n");
      out.write("/*\r\n");
      out.write("- Chart를 생성하면서, \r\n");
      out.write("- ctx를 첫번째 argument로 넘겨주고, \r\n");
      out.write("- 두번째 argument로 그림을 그릴때 필요한 요소들을 모두 넘겨줍니다. \r\n");
      out.write("*/\r\n");
      out.write("var myChart = new Chart(ctx, {\r\n");
      out.write("    type: 'bar',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: [\"맛\", \"배달\", \"서비스\"],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("            label: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("점 만족도',\r\n");
      out.write("            data: [");
      out.print(franflavor);
      out.write(',');
      out.write(' ');
      out.print(frandelivery);
      out.write(',');
      out.write(' ');
      out.print(franservice);
      out.write("],\r\n");
      out.write("            backgroundColor: [\r\n");
      out.write("                'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("                'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                'rgba(255, 206, 86, 0.2)'\r\n");
      out.write("                            ],\r\n");
      out.write("            borderColor: [\r\n");
      out.write("                'rgba(255,99,132,1)',\r\n");
      out.write("                'rgba(54, 162, 235, 1)',\r\n");
      out.write("                'rgba(255, 159, 64, 1)'\r\n");
      out.write("            ],\r\n");
      out.write("            borderWidth: 1\r\n");
      out.write("        }]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("        maintainAspectRatio: false, // default value. false일 경우 포함된 div의 크기에 맞춰서 그려짐.\r\n");
      out.write("        scales: {\r\n");
      out.write("            yAxes: [{\r\n");
      out.write("                ticks: {\r\n");
      out.write("                    beginAtZero:true\r\n");
      out.write("                }\r\n");
      out.write("            }]\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<div style=\"height: 500px; text-align: center;\">\r\n");
      out.write("\t\t<select id=\"selectBox\" style=\"float: right;\">\r\n");
      out.write("\t\t<option value=\"소비자평점\">소비자평점</option>\r\n");
      out.write("\t\t<option value=\"매출현황\">매출현황</option>\t\t\r\n");
      out.write("\t\t</select><br/>\r\n");
      out.write("\t\t\t<h2> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("의 지점평가</h2><br/>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">맛평점 평균 : ");
      out.print(franflavor );
      out.write("</h3>\r\n");
      out.write("\t\t\t<h4>전국 백다방 맛평점 평균 : ");
      out.print(flavor );
      out.write("</h4><br/>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">배달평점 평균 : ");
      out.print(frandelivery );
      out.write("</h3>\r\n");
      out.write("\t\t\t<h4>전국 백다방 배달평점 평균 : ");
      out.print(delivery );
      out.write("</h4><br/>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">서비스평점 평균 : ");
      out.print(franservice );
      out.write("</h3>\r\n");
      out.write("\t\t\t<h4>전국 백다방 서비스평점 평균 : ");
      out.print(service );
      out.write("</h4><br/>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">※개선방안※<br/><br/>\r\n");
      out.write("\t\t\t");
if(flavor-franflavor>0){
				
      out.write("맛에 조금더 신경써주세요!!<br/><br/>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
if(delivery-frandelivery>0){
				
      out.write("배달에 조금더 신경써주세요!!<br/><br/>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
if(service-franservice>0){
				
      out.write("서비스에 조금더 신경써주세요!!<br/><br/>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("</h3>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer id = \"footer\" class = \"footer\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".in_footer {\r\n");
      out.write("    border-top: 3px solid #ffe600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 1199px){\r\n");
      out.write(".container {\r\n");
      out.write("    width: calc(100% - 20px);\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("}}\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1150px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".in_footer {\r\n");
      out.write("    padding: 30px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #262626;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".in_footer .logo {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 179px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: inherit;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .company_info {\r\n");
      out.write("    padding-top: 30px;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    font-size: 0.812rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .r_box {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 175px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 30px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    font-size: 0.75rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 5px 7px;\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    border: 1px solid #262626;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    -webkit-appearance: menulist-button;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site #fmenu {\r\n");
      out.write("    display: none;\r\n");
      out.write("    padding: 0 5px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 28px;\r\n");
      out.write("    left: -1px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border: 1px solid #262626;\r\n");
      out.write("    width: 175px;\r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site #fmenu option {\r\n");
      out.write("    padding: 7px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\" style = \"margin-top:40px;\">\r\n");
      out.write("\t            <div class=\"in_footer\">\r\n");
      out.write("\t                <a class=\"logo\" href=\"http://paikdabang.com\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContex.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/theOne.png\" alt=\"더본로고\"></a>\r\n");
      out.write("\t                <div class=\"company_info\">\r\n");
      out.write("\t                    <ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>(주)ALLFORONE</li>\r\n");
      out.write("\t                        <li>사업자등록번호 010-2525-5858</li>\r\n");
      out.write("\t                        <li>대표이사 김태국</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>주소: 서울시 종로구 봉천동 1길 39 유성빌딩 5~6층</li>\r\n");
      out.write("\t                        <li>팩스: 02-511-3864</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t\t\t<ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>본사 대표전화: 010-3952-4545</li>\r\n");
      out.write("\t                        <li>가맹상담전화: 02-3447-0410</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>고객센터: 1544-2360</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <p class=\"copyright\">COPYRIGHTⓒ 2020 ALLFORONE KOREA INC. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"r_box\">\r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t\t\t<select id=\"fmenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" selected=\"\">패밀리 사이트 바로가기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://www.theborn.co.kr/\" target=\"_blank\">더본코리아 공식홈페이지</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://newmaul.com/\" target=\"_blank\">새마을식당</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://ssambap.co.kr/\" target=\"_blank\">원조쌈밥집</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://zzambbong.com/\" target=\"_blank\">홍콩반점</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://www.bornga.co.kr/\" target=\"_blank\">본가</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://hanshinpocha.com/\" target=\"_blank\">한신포차</a></option>\r\n");
      out.write("                                <option><a href=\"http://www.paiks-pan.com/\" target=\"_blank\">백철판</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://paiksbeer.com/\" target=\"_blank\">백스비어</a></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"http://www.udon0410.com/\" target=\"_blank\">역전우동</a></option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- TOP버튼 -->\r\n");
      out.write("\t\t\t\t<div class=\"to_top\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //TOP버튼 -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
