/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-09 08:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.paikdabang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.project.vo.*;
import com.project.vo.*;
import com.project.vo.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./header.jsp", Long.valueOf(1604869115471L));
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./includeFile.jsp", Long.valueOf(1604735771890L));
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./footer.jsp", Long.valueOf(1604859953588L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.project.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/index.css\"  />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
response.setContentType("text/html;charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"/>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.11.3.js\"></script> \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>빽다방 메인페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write(".bx-wrapper .bx-pager {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: .85em;\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: -10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){ \r\n");
      out.write("\r\n");
      out.write("var main = $('.bxslider').bxSlider({ \r\n");
      out.write("    mode: 'fade', \r\n");
      out.write("    auto: true,\t//자동으로 슬라이드 \r\n");
      out.write("    controls : true,\t//좌우 화살표\t\r\n");
      out.write("    autoControls: false,\t//stop,play \r\n");
      out.write("    pager:true,\t//페이징 \r\n");
      out.write("    pageSelector: '.pager',\r\n");
      out.write("    nextSelector: '.next-slide',\r\n");
      out.write("    nextText: '>', \r\n");
      out.write("    prevSelector: '.prev-slide',\r\n");
      out.write("    prevText: '<',\r\n");
      out.write("\r\n");
      out.write("    pause: 30000, \r\n");
      out.write("    autoDelay: 0,\t\r\n");
      out.write("    slideWidth: 1700,\r\n");
      out.write("    speed: 50, \r\n");
      out.write("    stopAutoOnclick:true,\r\n");
      out.write("\r\n");
      out.write("    onSlideBefore: function($slideElement, oldIndex, currentIndex){\r\n");
      out.write("\t\t$('.num').text((main.getCurrentSlide()+1)+\"/\"+main.getSlideCount());\r\n");
      out.write("    },\r\n");
      out.write("    \r\n");
      out.write("    onSlideAfter: function($slideElement, oldIndex, currentIndex){   \r\n");
      out.write("        \r\n");
      out.write("    \t // $('.num').text((main.getCurrentSlide()+1)+'/'+main.getSlideCount());  \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("\t}); \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("$(\".bx-stop\").click(function(){\t// 중지버튼 눌렀을때 \r\n");
      out.write("    main.stopAuto(); \r\n");
      out.write("    \r\n");
      out.write("    $(\".bx-start\").show(); \r\n");
      out.write("    return false; \r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("$(\".bx-start\").click(function(){\t//시작버튼 눌렀을때 \r\n");
      out.write("    main.startAuto(); \r\n");
      out.write("    \r\n");
      out.write("    $(\".bx-stop\").show(); \r\n");
      out.write("    return false; \r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("$( '.prev' ).on( 'click', function () {\r\n");
      out.write("\t   main.goToPrevSlide();  //이전 슬라이드 배너로 이동\r\n");
      out.write("\t   return false;              //<a>에 링크 차단\r\n");
      out.write("\t  });\r\n");
      out.write("\r\n");
      out.write("\t    //다음 버튼을 클릭하면 다음 슬라이드로 전환\r\n");
      out.write("\t  $( '.next' ).on( 'click', function () {\r\n");
      out.write("\t   main.goToNextSlide();  //다음 슬라이드 배너로 이동\r\n");
      out.write("\t   return false;\r\n");
      out.write("\t  } );\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  var didScroll;\r\n");
      out.write("\t  var lastScrollTop = 0;\r\n");
      out.write("\t  var delta = 5;\r\n");
      out.write("\t  var navbarHeight = $('header').outerHeight();\r\n");
      out.write("\r\n");
      out.write("\t  $(window).scroll(function(event){\r\n");
      out.write("\t      didScroll = true;\r\n");
      out.write("\t  });\r\n");
      out.write("\r\n");
      out.write("\t  setInterval(function() {\r\n");
      out.write("\t      if (didScroll) {\r\n");
      out.write("\t          hasScrolled();\r\n");
      out.write("\t          didScroll = false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t  }, 250);\r\n");
      out.write("\r\n");
      out.write("\t  function hasScrolled() {\r\n");
      out.write("\t      var st = $(this).scrollTop();\r\n");
      out.write("\t      \r\n");
      out.write("\t      // Make sure they scroll more than delta\r\n");
      out.write("\t      if(Math.abs(lastScrollTop - st) <= delta)\r\n");
      out.write("\t          return;\r\n");
      out.write("\t      \r\n");
      out.write("\t      // If they scrolled down and are past the navbar, add class .nav-up.\r\n");
      out.write("\t      // This is necessary so you never see what is \"behind\" the navbar.\r\n");
      out.write("\t      if (st > lastScrollTop && st > navbarHeight){\r\n");
      out.write("\t          // Scroll Down\r\n");
      out.write("\t          $('header').removeClass('.header').addClass('nav-up');\r\n");
      out.write("\t      } else {\r\n");
      out.write("\t          // Scroll Up\r\n");
      out.write("\t          if(st + $(window).height() < $(document).height()) {\r\n");
      out.write("\t              $('header').removeClass('nav-up').addClass('header');\r\n");
      out.write("\t          }\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t      lastScrollTop = st;\r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	//System.out.println(request.getServletContext()); 
	//ArrayList<OrderVO> productlist = (ArrayList<OrderVO>)request.getAttribute("productlist");
//	ArrayList<Integer> bestmenu =(ArrayList<Integer>)request.getAttribute("bestmenu");
//	System.out.println("index bestmenu" + bestmenu);
	List<ProductVO> bestProducts = null;
//	if(bestmenu.get(0)!= 0 || bestmenu.get(1) != 0 || bestmenu.get(2) != 0){
//		bestProducts = (List<ProductVO>)request.getAttribute("bestProducts");
//	}

	List<ProductVO> bestproduts = (List<ProductVO>)session.getAttribute("bestproduts");   //Null Pointer
	   
	 if(bestproduts != null){      
		   session.removeAttribute("bestproduts");   
		   session.setAttribute("bestproduts", bestProducts);
	  }else{      
		  
		//  bestProducts.add(0, new ProductVO().setIdx(0));
		  session.setAttribute("bestproduts", bestProducts); 
		  
	  }   


      out.write("\r\n");
      out.write("<header id = \"header\" class=\"header\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/header.css\">\r\n");
      out.write("\r\n");
      out.write("<title>빽다방 헤더</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	String franchiseid = null;
	String franchisekey = (String) session.getAttribute("franchisekey");
	MemberVO member = null;
	String selectmenu = null;
	String myfkKey = null;
	String mydefaultTier = null;
	String mymymymymenu = (String)session.getAttribute("superSonny");
	System.out.println("사장님이 선택한 메뉴: " + mymymymymenu);
try {
	franchiseid = (String) session.getAttribute("franchiseid");
	selectmenu = (String) request.getAttribute("menu");
	member = (MemberVO) session.getAttribute("loginMember");
	myfkKey = member.getFranchisekey();
	mydefaultTier = member.getTier();
} catch (Exception e) {
	franchiseid = "customer";
	member = new MemberVO();
	member.setIdx(0);
	member.setId("none");
	myfkKey = "a";
	mydefaultTier = "customer";
}



      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\" style=\"display: inline-flex; margin-bottom: 40px; padding: 25px 6px 0px;\">\r\n");
      out.write("\t<div class = \"subNash\">\r\n");
      out.write("\t\t<a href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/gotoPaikDabang.do?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(mydefaultTier );
      out.write("\" class=\"logo\" style = \"position: relative;  top: 30px;right:-20px;\"> \r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<img src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/DABANG-logo (1).png\" style=\"width: 149px;\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"main-menu\" style = \"position: relative;right: -200px;top: -50px;z-index: 1;\">\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/menu.do?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">메뉴</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul id = \"sub-menuT\" class = \"sub-menuT\" style=\"z-index: 1; display: inline-grid; list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/coffee?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">커피</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/dessert?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">아이스크림/디저트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/beverage?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">음료</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/drink?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">빽스치노</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a href=\"\">소식</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id = \"sub-menuT\" class= \"sub-menuT\" style=\"z-index: 1; display: inline-grid; list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/util/findPerson.do\">구인공고</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">우수 친절매장</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/come/to/mystore?franchisekey=");
      out.print(franchisekey);
      out.write("\" style = \"position: relative; right: 0px;   top: -4px;width:115px;\">매장안내</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				if (franchisekey.equals(myfkKey)) {
				//System.out.println("사장님 들어옴...");
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a style = \"position: relative;right: 0px;top: -4px;width:115px;\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/resources/order?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">재고주문</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a style = \"position: relative;right: 0px;top: -4px;width:115px;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/resources/chart?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">지점평가\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				} else if ("customer".equals(mydefaultTier)) {
			System.out.println("일반소비자");
			}
			
      out.write("\r\n");
      out.write("\t\t\t");
 if(member != null) {
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a style = \"position: relative;right: 0px;top: -4px;width:114px;\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/basket?id=");
      out.print(member.getId());
      out.write("\">장바구니</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} else if(member == null) {
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a style = \"position: relative;right: 0px;top: -4px;width:114px;\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/basket\">장바구니</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"home__slider\"> \r\n");
      out.write("    \t\t<div class=\"bxslider\"> \r\n");
      out.write("        \t\t<div>\r\n");
      out.write("        \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/main_귀묘한스무디 (1).jpg\" alt=\"그림1\" data-slide-index=\"0\">\r\n");
      out.write("        \t\t\t<div class=\"mst_wrap\">\r\n");
      out.write("                    \t<div class=\"txt_slider\">\r\n");
      out.write("                        \t<div>\r\n");
      out.write("                            \t\r\n");
      out.write("                        \t</div>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("        \t\t<div>\r\n");
      out.write("        \t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/main_곡물3종.jpg\" alt=\"그림2\" data-slide-index=\"1\">\r\n");
      out.write("        \t\t\t<div class=\"mst_wrap\">\r\n");
      out.write("                    \t<div class=\"txt_slider\">\r\n");
      out.write("                        \t<div>\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t</div>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                \t</div>\r\n");
      out.write("        \t\t</div> \r\n");
      out.write("        \t\t<div>\r\n");
      out.write("\t        \t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/main_한끼라떼.jpg\" alt=\"그림2\" data-slide-index=\"2\">\r\n");
      out.write("        \t\t\t<div class=\"mst_wrap\">\r\n");
      out.write("                    \t<div class=\"txt_slider\">\r\n");
      out.write("                        \t<div>\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t</div>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                \t</div>\r\n");
      out.write("        \t\t</div> \r\n");
      out.write("    \t\t</div> \r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<div class = \"slider_btn slider_btn01\" style = \"display:-webkit-inline-box;\">\r\n");
      out.write("    \t\t\t<p class = \"num\"><a style = \"margin:-5px auto;\">1/3</a></p>\r\n");
      out.write("    \t\t\t<p class = \"prev\">\r\n");
      out.write("    \t\t\t\t<a class=\"bx-prev\" href=\"\" style = \"margin:-2px auto; line-height:0px;\"><i class=\"fas fa-angle-left\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("    \t\t\t</p>\r\n");
      out.write("    \t\t\t<p class=\"next\" ><a class=\"bx-next\" href=\"\" style = \"margin:-2px auto; line-height:0px;\"><i class=\"fas fa-angle-right\" aria-hidden=\"true\"></i></a></p>\r\n");
      out.write("    \t\t\t<p class=\"auto\">\r\n");
      out.write("    \t\t\t\t<a class=\"bx-start\" href=\"\" style = \"margin:-2px auto; line-height:0px;\">\r\n");
      out.write("    \t\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t</p>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t<p class = \"autoStop\">\r\n");
      out.write(" \t\t\t\t\t<a class=\"bx-stop\" href=\"\"  style = \"margin:-2px auto; line-height:0px;\">\r\n");
      out.write("    \t\t\t\t\t<i class=\"fa fa-pause\" aria-hidden=\"true\"></i>\r\n");
      out.write("    \t\t\t\t</a>\r\n");
      out.write("    \t\t\t</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class = \"grid_wrap clear\" style = \"margin: 0 auto; position: relative; left: -170px;\">\r\n");
      out.write("\t\t<div class=  \"r_box\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"l_box clear\" style = \"text-align:center;\">\r\n");
      out.write("                <div class=\"l_inner\">\r\n");
      out.write("                    <h1 class=\"main_tit2 color-1\">store</h1>\r\n");
      out.write("                    <p class=\"font-l\">원하시는 지역의 매장을 검색해 보세요!</p>\r\n");
      out.write("                    <div class=\"store_search\">\r\n");
      out.write("                        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/gotostores.do\" method=\"get\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"search_string\" placeholder=\"Find a store in your area!\">\r\n");
      out.write("                            <button class=\"ok\" type=\"submit\" name=\"\"><img src=\"http://paikdabang.com/wp-content/themes/paikdabang/assets/images/search-ico.png\" alt=\"검색\"></button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"l_inner\">\r\n");
      out.write("                    <h1 class=\"main_tit2 color-1\">franchise</h1>\r\n");
      out.write("                    <p class=\"font-l\">빽다방 창업안내를 도와드리겠습니다.</p>\r\n");
      out.write("                    <a class=\"btn st-1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/launchbusiness.do\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"main_sec row-4\" style =\"text-align:center;\">\r\n");
      out.write("        <div class=\"sns_section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <p class=\"font-2\">PAIK’S COFFEE SNS</p>\r\n");
      out.write("                    <p class=\"tag\"><span>#빽다방</span><span>#빽다방신메뉴</span><span>#빽다방이벤트</span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"sns_ico\" style = \"display:inline-flex; list-style:none;margin-top:20px;\">\r\n");
      out.write("                    <li><a href=\"https://ko-kr.facebook.com/ipaikscoffee/\" target=\"_blank\"><img src=\"http://paikdabang.com/wp-content/themes/paikdabang/assets/images/facebook-ico.png\" alt=\"facebook\"></a></li>\r\n");
      out.write("                    <li><a href=\"https://www.instagram.com/paikscoffee_official/\" target=\"_blank\"><img style = \"margin-left:30px;\" src=\"http://paikdabang.com/wp-content/themes/paikdabang/assets/images/insta-ico.png\" alt=\"instagram\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<footer id = \"footer\" class = \"footer\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".in_footer {\r\n");
      out.write("    border-top: 3px solid blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 1199px){\r\n");
      out.write(".container {\r\n");
      out.write("    width: calc(100% - 20px);\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("}}\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1150px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".in_footer {\r\n");
      out.write("    padding: 30px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #262626;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".in_footer .logo {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 179px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: inherit;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .company_info {\r\n");
      out.write("    padding-top: 30px;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    font-size: 0.812rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .r_box {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 175px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 30px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    font-size: 0.75rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 5px 7px;\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    border: 1px solid #262626;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    -webkit-appearance: menulist-button;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site #fmenu {\r\n");
      out.write("    display: none;\r\n");
      out.write("    padding: 0 5px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 28px;\r\n");
      out.write("    left: -1px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border: 1px solid #262626;\r\n");
      out.write("    width: 175px;\r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site #fmenu option {\r\n");
      out.write("    padding: 7px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");

TempVO mymymymymymyown = (TempVO)session.getAttribute("mydabangbusiness"); //nullpointer
String myAddr = mymymymymymyown.getAddress();	//nullpointer
if(mymymymymymyown.getDetailaddress()!=null){
	myAddr += " " + mymymymymymyown.getDetailaddress();
}

      out.write("\r\n");
      out.write("\t<div class=\"container\" style = \"margin-top:40px;\">\r\n");
      out.write("\t            <div class=\"in_footer\">\r\n");
      out.write("\t                <a class=\"logo\" href=\"\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContex.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/DABANG-logo (1).png\" alt=\"다방로고\" style = \"width:149px;\"></a>\r\n");
      out.write("\t                <div class=\"company_info\">\r\n");
      out.write("\t                    <ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>(주)THE ONE</li>\r\n");
      out.write("\t                        <li>사업자등록번호 ");
      out.print(mymymymymymyown.getPhone() );
      out.write("</li>\r\n");
      out.write("\t                        <li>대표이사 ");
      out.print(mymymymymymyown.getName() );
      out.write("</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>주소: ");
      out.print(myAddr );
      out.write("</li>\r\n");
      out.write("\t                        <li>팩스: 02-511-3864</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t\t\t<ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>본사 대표전화: 010-3952-4545</li>\r\n");
      out.write("\t                        <li>가맹상담전화: 02-3447-0410</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>고객센터: 1544-2360</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <p class=\"copyright\">COPYRIGHTⓒ 2020 THE ONE KOREA INC. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"r_box\">\r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t\t\t<select id=\"fmenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" selected=\"\">더원코리아 공식홈페이지</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter\" target=\"_blank\">더본코리아 공식홈페이지</a></option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- TOP버튼 -->\r\n");
      out.write("\t\t\t\t<div class=\"to_top\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //TOP버튼 -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
