/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-08 17:26:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.paikdabang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.DecimalFormat;
import com.project.vo.ProductVO;
import com.project.service.*;
import com.project.vo.*;
import com.project.vo.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-8.5.57/wtpwebapps/theOne/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1600329454716L));
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./header.jsp", Long.valueOf(1604784813349L));
    _jspx_dependants.put("/WEB-INF/views/paikdabang/./footer.jsp", Long.valueOf(1604782753541L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.project.service");
    _jspx_imports_packages.add("com.project.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("com.project.vo.ProductVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/menu.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/itemlist.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<title>빽다방 전체 상품</title>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/menu.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String mymenu = (String) request.getAttribute("selectmenu");
	InventoryService inventory = (InventoryService)request.getAttribute("inventoryService");
	List<ProductVO> list = (List<ProductVO>) request.getAttribute("menulist");

	List<ProductVO> coffeelist = (List<ProductVO>) request.getAttribute("coffeelist");
	List<ProductVO> beveragelist = (List<ProductVO>) request.getAttribute("beveragelist");
	List<ProductVO> dessertlist = (List<ProductVO>) request.getAttribute("dessertlist");
	List<ProductVO> drinklist = (List<ProductVO>) request.getAttribute("drinklist");

	String menu = (String) request.getAttribute("menu");

	DecimalFormat df = new DecimalFormat("###,###");
	
      out.write("\r\n");
      out.write("\t<header class=\"header\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/paikdabang/header.css\">\r\n");
      out.write("\r\n");
      out.write("<title>빽다방 헤더</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	String franchiseid = null;
	String franchisekey = (String) session.getAttribute("franchisekey");
	MemberVO member = null;
	String selectmenu = null;
	String myfkKey = null;
	String mydefaultTier = null;
	String mymymymymenu = (String)session.getAttribute("superSonny");
	System.out.println("사장님이 선택한 메뉴: " + mymymymymenu);
try {
	franchiseid = (String) session.getAttribute("franchiseid");
	selectmenu = (String) request.getAttribute("menu");
	member = (MemberVO) session.getAttribute("loginMember");
	myfkKey = member.getFranchisekey();
	mydefaultTier = member.getTier();
} catch (Exception e) {
	franchiseid = "customer";
	member = new MemberVO();
	member.setIdx(0);
	member.setId("none");
	myfkKey = "a";
	mydefaultTier = "customer";
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\" style=\"display: inline-flex; margin-bottom: 40px; padding: 25px 6px 0px;\">\r\n");
      out.write("\t<div class = \"subNash\">\r\n");
      out.write("\t\t<a href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/gotoPaikDabang.do?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchiseid);
      out.write("&tier=");
      out.print(mydefaultTier );
      out.write("\" class=\"logo\" style = \"position: relative;  top: 30px;right:-20px;\"> \r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<img src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/DABANG-logo (1).png\" style=\"width: 149px;\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"main-menu\" style = \"position: relative;right: -200px;top: -50px;z-index: 1;\">\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/menu.do?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">메뉴</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul id = \"sub-menuT\" class = \"sub-menuT\" style=\"z-index: 1; display: inline-grid; list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/coffee?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">커피</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/dessert?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">아이스크림/디저트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/beverage?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">음료</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/drink?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("\">빽스치노</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a href=\"\">소식</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id = \"sub-menuT\" class= \"sub-menuT\" style=\"z-index: 1; display: inline-grid; list-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/util/findPerson.do\">구인공고</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">우수 친절매장</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/come/to/mystore?franchisekey=");
      out.print(franchisekey);
      out.write("\" style = \"position: relative; right: 0px;   top: -4px;width:115px;\">매장안내</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				if (franchisekey.equals(myfkKey)) {
				//System.out.println("사장님 들어옴...");
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a style = \"position: relative;right: 0px;top: -4px;width:115px;\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/resources/order?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">재고주문</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\">\r\n");
      out.write("\t\t\t\t\t<a style = \"position: relative;right: 0px;top: -4px;width:115px;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/resources/chart?selectmenu=");
      out.print(mymymymymenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">지점평가\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				} else if ("customer".equals(mydefaultTier)) {
			System.out.println("일반소비자");
			}
			
      out.write("\r\n");
      out.write("\t\t\t");
 if(member != null) {
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a style = \"position: relative;right: 0px;top: -4px;width:114px;\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/basket?id=");
      out.print(member.getId());
      out.write("\">장바구니</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} else if(member == null) {
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t<li style=\"list-style: none;\"><a style = \"position: relative;right: 0px;top: -4px;width:114px;\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/basket\">장바구니</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- http://paikdabang.com/wp-content/images/bg-menu.jpg -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"pattern\" class=\"pattern\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h2 style=\"margin: 0 auto;\">상품목록</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"list img-list\">\r\n");
      out.write("        ");

            for (int i = 0; i < list.size(); i++) {
         
      out.write("\r\n");
      out.write("         <li>\r\n");
      out.write("            ");
 if (inventory.getSoldOutInt(list.get(i).getIdx(), franchisekey) > 0){ 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/dabang/itemdetail?idx=");
      out.print(list.get(i).getIdx());
      out.write("\" class=\"inner\">\r\n");
      out.write("               <div class=\"li-img\">\r\n");
      out.write("                     <img\r\n");
      out.write("                     src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/");
      out.print(list.get(i).getImage() );
      out.write("\"\r\n");
      out.write("                     alt=\"Image Alt Text\" />\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"li-text\">\r\n");
      out.write("                  <h4 class=\"li-head\">");
      out.print(list.get(i).getMenu());
      out.write('(');
      out.print(list.get(i).getTemp());
      out.write(")\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <strong>");
      out.print(df.format(list.get(i).getPrice()));
      out.write(" 원</strong>\r\n");
      out.write("               </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
} else { 
      out.write("\r\n");
      out.write("               <div class=\"li-img\">\r\n");
      out.write("                     <img\r\n");
      out.write("                     src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Sold_Out.png\"\r\n");
      out.write("                     alt=\"Image Alt Text\" />\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"li-text\">\r\n");
      out.write("                  <h4 class=\"li-head\">");
      out.print(list.get(i).getMenu());
      out.write('(');
      out.print(list.get(i).getTemp());
      out.write(")\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <strong>");
      out.print(df.format(list.get(i).getPrice()));
      out.write(" 원</strong>\r\n");
      out.write("               </div>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("         </li>\r\n");
      out.write("         ");

            }
         
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".in_footer {\r\n");
      out.write("    border-top: 3px solid blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 1199px){\r\n");
      out.write(".container {\r\n");
      out.write("    width: calc(100% - 20px);\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("}}\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1150px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".in_footer {\r\n");
      out.write("    padding: 30px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #262626;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".in_footer .logo {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 179px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: inherit;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .company_info {\r\n");
      out.write("    padding-top: 30px;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    font-size: 0.812rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .r_box {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 175px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 30px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    font-size: 0.75rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 5px 7px;\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    border: 1px solid #262626;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    -webkit-appearance: menulist-button;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site #fmenu {\r\n");
      out.write("    display: none;\r\n");
      out.write("    padding: 0 5px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 28px;\r\n");
      out.write("    left: -1px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border: 1px solid #262626;\r\n");
      out.write("    width: 175px;\r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_footer .family_site #fmenu option {\r\n");
      out.write("    padding: 7px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");

TempVO mymymymymymyown = (TempVO)session.getAttribute("mydabangbusiness"); 
String myAddr = mymymymymymyown.getAddress();
if(mymymymymymyown.getDetailaddress()!=null){
	myAddr += " " + mymymymymymyown.getDetailaddress();
}

      out.write("\r\n");
      out.write("\t<div class=\"container\" style = \"margin-top:40px;\">\r\n");
      out.write("\t            <div class=\"in_footer\">\r\n");
      out.write("\t                <a class=\"logo\" href=\"http://paikdabang.com\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContex.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/paikdabang/DABANG-logo (1).png\" alt=\"다방로고\" style = \"width:149px;\"></a>\r\n");
      out.write("\t                <div class=\"company_info\">\r\n");
      out.write("\t                    <ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>(주)THE ONE</li>\r\n");
      out.write("\t                        <li>사업자등록번호 ");
      out.print(mymymymymymyown.getPhone() );
      out.write("</li>\r\n");
      out.write("\t                        <li>대표이사 ");
      out.print(mymymymymymyown.getName() );
      out.write("</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>주소: ");
      out.print(myAddr );
      out.write("</li>\r\n");
      out.write("\t                        <li>팩스: 02-511-3864</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t\t\t<ul style = \"list-style:none;\">\r\n");
      out.write("\t                        <li>본사 대표전화: 010-3952-4545</li>\r\n");
      out.write("\t                        <li>가맹상담전화: 02-3447-0410</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>고객센터: 1544-2360</li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <p class=\"copyright\">COPYRIGHTⓒ 2020 THE ONE KOREA INC. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"r_box\">\r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t\t\t<select id=\"fmenu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" selected=\"\">더원코리아 공식홈페이지</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter\" target=\"_blank\">더본코리아 공식홈페이지</a></option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- TOP버튼 -->\r\n");
      out.write("\t\t\t\t<div class=\"to_top\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //TOP버튼 -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
