/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-04 08:16:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hanshin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.project.vo.*;
import com.project.service.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/hanshin/./header.jsp", Long.valueOf(1604477701818L));
    _jspx_dependants.put("/WEB-INF/views/hanshin/./footer.jsp", Long.valueOf(1604038862000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.project.vo");
    _jspx_imports_packages.add("com.project.service");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>한신포차</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/hanshin/hanshinmain.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/hanshin/swiper.css\"/>\r\n");
      out.write("\t<!-- Link Swiper's CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://swiperjs.com/package/swiper-bundle.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
System.out.println(request.getServletContext()); 
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>한신포차</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/hanshin/header.css\"/>\r\n");
      out.write("\t<!-- Link Swiper's CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://swiperjs.com/package/swiper-bundle.min.css\">\r\n");
      out.write("</head>\r\n");

	TempService tempservice = (TempService)request.getAttribute("tempserviceABC");
	String franchiseid = null;
	String franchisekey = (String) session.getAttribute("franchisekey");
	MemberVO member = null;
	String selectmenu = null;
	String myfkKey = null;
	String mydefaultTier = null;
	TempVO myown = null;
	
try {
	franchiseid = (String) session.getAttribute("franchiseid");
	selectmenu = (String) request.getAttribute("menu");
	member = (MemberVO) session.getAttribute("loginMember");
	myfkKey = member.getFranchisekey();
	mydefaultTier = member.getTier();
	myown = tempservice.findmyBusiness(franchisekey);
	System.out.println("myown: " + myown.toString());
	System.out.println("myown.selectmenu(): " + myown.getSelectmenu());
	System.out.println("myown.contractNo(): " + myown.getContractno());
} catch (Exception e) {
	franchiseid = "customer";
	member = new MemberVO();
	member.setIdx(0);
	member.setId("none");
	myfkKey = "a";
	mydefaultTier = "customer";
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"header_content\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/hanshin/gotoHanshin.do\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/hanshin/logo.png\"/>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/hanshin/menu?selectmenu=");
      out.print(selectmenu);
      out.write("\">메뉴</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/hanshin/come/to/mystore?contractno=");
      out.print(myown.getContractno() );
      out.write("\">매장 안내</a>\r\n");
      out.write("\t\t\t\t\t</li> \t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/hanshin/basket?id=");
      out.print(member.getId());
      out.write("\">장바구니</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">후기 게시판</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/hanshin/resources/order?selectmenu=");
      out.print(selectmenu);
      out.write("&franchisekey=");
      out.print(franchisekey);
      out.write("&tier=");
      out.print(member.getTier());
      out.write("\">재고 관리</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">매출 분석</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t<button></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Swiper JS -->\r\n");
      out.write("\t<script src=\"https://swiperjs.com/package/swiper-bundle.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Initialize Swiper -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar swiper = new Swiper('.swiper-container', {\r\n");
      out.write("\r\n");
      out.write("\t\t\tautoplay: {\r\n");
      out.write("\t\t\t\tdelay: 3000,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\tloop:true,\r\n");
      out.write("\t\t\tspaceBetween: 30,\r\n");
      out.write("\t\t\tpagination: {\r\n");
      out.write("\t\t\t\tel: '.swiper-pagination',\r\n");
      out.write("\t\t\t\tclickable: true,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("  \t\r\n");
      out.write("\t<!-- Body -->\r\n");
      out.write("\t\t\t<!-- 헤더 아래 슬라이드 이미지 -->\r\n");
      out.write("\t\t<div class=\"swiper-container\">\r\n");
      out.write("\t\t\t<div class=\"swiper-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"swiper-slide\" id=\"slide1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"main_text_h2\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"slide_sentence\">\r\n");
      out.write("\t\t\t\t\t\t\tNEVER BEEN<br/>\r\n");
      out.write("\t\t\t\t\t\t\tCLOSED<br/>\r\n");
      out.write("\t\t\t\t\t\t\tSINCE 1998\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"main_text_p\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"slide_sentence\">\r\n");
      out.write("\t\t\t\t\t\t\t1980년~1990년 후반까지 길거리에서 쉽게 볼 수 있던 포장마차는 퇴근길 맛있는 안주로 출출함을 달래주고 피로를 녹여주었으며,<br/>\r\n");
      out.write("\t\t\t\t\t\t\t특유의 정겨운 분위기로 많은 이들의 발걸음을 붙잡았습니다. 한신포차는 이러한 길거리 포장마차의 분위기를 실내<br/>\r\n");
      out.write("\t\t\t\t\t\t\t에 연출한 대한민국 최초의 대형 실내 포장마차로써,<br/>\r\n");
      out.write("\t\t\t\t\t\t\t20여 년이 흐른 오늘날까지 특유의 분위기와 한신닭발, 옛날통닭, 해물모둠볶음 등의 특별한 안주로 많은 사랑을 받고 있습니다.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"swiper-slide\" id=\"slide2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"main_text_h2\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"slide_sentence\">\r\n");
      out.write("\t\t\t\t\t\t\t멈출수 없는<br/>\r\n");
      out.write("\t\t\t\t\t\t\t매력의 매운맛,<br/>\r\n");
      out.write("\t\t\t\t\t\t\t한신닭발\r\n");
      out.write("\t\t\t\t\t\t</h2>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"main_text_p\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"slide_sentence\">\r\n");
      out.write("\t\t\t\t\t\t\t보글보글 끓여 먹는 매운 국물 닭발의 원조! 한신닭발은 화끈하고 부드러운 맛으로 많은 사랑을 받고 있는 한신포차의 대표 메뉴입니다. 콩나물<br/>\r\n");
      out.write("\t\t\t\t\t\t\t을 넣어 아삭한 식감을 더하고, 동글동글 직접 만들어 먹는 셀프주먹밥을 추가하여 맛을 한층 더 풍부하게, 그리고 닭발을 다 먹은 후 남은 양념<br/>\r\n");
      out.write("\t\t\t\t\t\t\t에 밥을 볶아 마무리 하며 한신닭발을 완벽하게 즐겨보세요!\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"swiper-slide\" id=\"slide3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"main_text_h2\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"slide_sentence\">\r\n");
      out.write("\t\t\t\t\t\t\t대한민국<br/>\r\n");
      out.write("\t\t\t\t\t\t\t대표 실내 포장마차<br/>\r\n");
      out.write("\t\t\t\t\t\t\t한신포차\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"main_text_p\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"slide_sentence\">\r\n");
      out.write("\t\t\t\t\t\t\t북적대는 포차 속 정겨운 사람 냄새, 주방에서 들려오는 맛있는 소리,<br/>\r\n");
      out.write("\t\t\t\t\t\t\t특별한 안주가 어우러져 누구나 부담없이<br/>\r\n");
      out.write("\t\t\t\t\t\t\t술잔을 기울일 수 있는 편안함이 있습니다.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Add Pagination -->\r\n");
      out.write("\t\t\t<div class=\"swiper-pagination\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"bodyContent\">\r\n");
      out.write("\t\t<div class=\"menu1\">\r\n");
      out.write("\t\t\t<div class=\"signatureMenuDetail1\">\r\n");
      out.write("\t\t\t\t<h2>한신 닭발</h2>\r\n");
      out.write("\t\t\t\t<h3>중독성 강한 한신포차의 대표메뉴!</h3>\r\n");
      out.write("\t\t\t\t<p>보글보글 끓여먹는 매운 닭발 메뉴입니다.<br/>\r\n");
      out.write("\t\t\t\t      콩나물을 넣어 아삭한 식감을 더하고,<br/>\r\n");
      out.write("\t\t\t\t      매운 맛을 잡아주는 셀프주먹밥과<br/>\r\n");
      out.write("\t\t\t\t      함께 드시면 더욱 맛있습니다.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"signatureMenuImg1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"menu2\">\r\n");
      out.write("\t\t\t<div class=\"signatureMenuDetail2\">\r\n");
      out.write("\t\t\t\t<h2>치즈돼지고추장바베큐</h2>\r\n");
      out.write("\t\t\t\t<h3>매콤 바베큐 &<br/>모짜렐라 치즈의 완벽한 조화!</h3>\r\n");
      out.write("\t\t\t\t<p>직화로 구워낸 매콤한 양념의 돼지고기를<br/>\r\n");
      out.write("\t\t\t\t      모짜렐라 치즈와 함께 먹는 메뉴입니다.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"signatureMenuImg2\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"menu3\">\r\n");
      out.write("\t\t\t<div class=\"signatureMenuDetail3\">\r\n");
      out.write("\t\t\t\t<h2>해물모둠볶음</h2>\r\n");
      out.write("\t\t\t\t<h3>튀긴 소면 위에 푸짐한<br/>\r\n");
      out.write("\t\t\t\t\t해물이 한 가득!</h3>\r\n");
      out.write("\t\t\t\t<p>접시 모양의 소면 튀김 위에 다양한 해산물,<br/>\r\n");
      out.write("\t\t\t\t       야채를 푸짐하게 볶아 올린 메뉴입니다.<br/>\r\n");
      out.write("\t\t\t\t   Tip. 남은 소스에 소면을 비벼 드셔보세요!\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"signatureMenuImg3\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>한신포차</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".footer_wrap {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 30px 0 45px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("    width: 1109px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div>p:nth-child(2) {\r\n");
      out.write("    margin: 10px 0 8px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("    color: #666666;\r\n");
      out.write("    word-break: keep-all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div>p:last-child {\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    color: #999999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>.brand-site {\r\n");
      out.write("    float: right;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".mmenu, .mmenu_list {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div>ul::after {\r\n");
      out.write("    display: block;\r\n");
      out.write("    clear: both;\r\n");
      out.write("    content: '';\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div>ul>li>a {\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div>ul>li::after {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    content: '|';\r\n");
      out.write("    font-size: 10px;\r\n");
      out.write("    color: #cccccc;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>div>ul>li:last-child::after {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("element.style {\r\n");
      out.write("}\r\n");
      out.write(".footer {\r\n");
      out.write("    width: 1109px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    font-family: 'NanumBarunGothic';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".footer::after {\r\n");
      out.write("    display: block;\r\n");
      out.write("    clear: both;\r\n");
      out.write("    content: '';\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer>h1 {\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-right: 92px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".footer>div>ul>li {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"footer_wrap\">\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<h1 class=\"logo\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/theOne.png\" alt=\"푸터로고\">\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span class=\"txt\">(주)더원코리아</span><span class=\"bar\">|</span><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"txt\">사업자등록번호 211-86-00870</span><span class=\"bar\">|</span><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"txt\">대표이사 김태국</span> <br>\r\n");
      out.write("\t\t\t\t\t<span class=\"txt\">주소: 서울시 강남구 봉은사로 1길 39 유성빌딩 5~6층</span><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"bar\">|</span><span class=\"txt\">팩스: 02-511-3864</span> <br>\r\n");
      out.write("\t\t\t\t\t<span class=\"txt\">본사 대표전화 및 가맹상담전화 : 02-549-3864</span><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"bar\">|</span><span class=\"txt\">빽다방 가맹상담전화:\r\n");
      out.write("\t\t\t\t\t\t02-3447-0410</span><span class=\"bar\">|</span><span class=\"txt\">고객센터:\r\n");
      out.write("\t\t\t\t\t\t1544-2360</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>COPYRIGHTⓒ 2017 THEBORN KOREA INC. ALL RIGHTS RESERVED</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"brand-site\">\r\n");
      out.write("\t\t\t\t<select name=\"\" id=\"goto_familiy_site\" onchange=\"if(this.selectedIndex){this.blur();window.open(options[selectedIndex].value);}\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\" selected=\"\">패밀리 사이트 바로가기</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://newmaul.com/\">새마을식당</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"http://localhost:8080/product/dabang/gotoPaikDabang.do\">빽다방</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://zzambbong.com/\">홍콩반점</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.bornga.co.kr/\">본가</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://localhost:8080/product/hanshin/gotoHanshin.do\">한신포차</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://www.paiks-pan.com/\">백철판</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://paiksbeer.com/\">백스비어</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"http://dolbaegi.com/\">돌배기집</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Swiper JS -->\r\n");
      out.write("\t<script src=\"https://swiperjs.com/package/swiper-bundle.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Initialize Swiper -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar swiper = new Swiper('.swiper-container', {\r\n");
      out.write("\r\n");
      out.write("\t\t\tautoplay: {\r\n");
      out.write("\t\t\t\tdelay: 3000,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\tloop:true,\r\n");
      out.write("\t\t\tspaceBetween: 30,\r\n");
      out.write("\t\t\tpagination: {\r\n");
      out.write("\t\t\t\tel: '.swiper-pagination',\r\n");
      out.write("\t\t\t\tclickable: true,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
