/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-09 13:14:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.project.vo.SurveyVO;
import java.util.ArrayList;
import com.project.vo.OrderVO;
import com.project.vo.IncomeVO;
import org.springframework.ui.Model;
import java.text.DecimalFormat;

public final class theonechart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.vo.OrderVO");
    _jspx_imports_classes.add("org.springframework.ui.Model");
    _jspx_imports_classes.add("com.project.vo.SurveyVO");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("com.project.vo.IncomeVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<IncomeVO>	list = (ArrayList<IncomeVO>)request.getAttribute("theoneprice");
ArrayList<OrderVO>	list1 = (ArrayList<OrderVO>)request.getAttribute("paiksprice");	
ArrayList<OrderVO> list2 = (ArrayList<OrderVO>)request.getAttribute("hanshinprice");
int theoneprice = 0;
int paiksprice = 0;
int hanshinprice = 0;
DecimalFormat df = new DecimalFormat("###,###");
for(int i=0;i<list.size();i++) {
	theoneprice += list.get(i).getProfit();
}
for(int i=0;i<list1.size();i++) {
	paiksprice += (int)list1.get(i).getSumPrice();
}

for(int i = 0; i < list2.size();i++){
	hanshinprice += (int)list2.get(i).getSumPrice();
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.8.0\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script>   <!-- 달력 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/headquarter/headquarterAdmin.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function() {\r\n");
      out.write("      $(\"#datepicker1\").flatpickr();\r\n");
      out.write("      $(\"#datepicker2\").flatpickr();\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"sub_header sub_bg05\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p class=\"company\">THEONE</p>\r\n");
      out.write("\t\t\t\t<p class=\"sub_tit\">관리자페이지</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav role=\"navigation\">\r\n");
      out.write("  <ul id=\"main-menu\">\r\n");
      out.write("    <li><a href=\"#\">매출현황</a>\r\n");
      out.write("    \t<ul id=\"sub-menu\">\r\n");
      out.write("      \t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/theonechart.do\" aria-label=\"subemnu\">기간별 매출</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/theonescore.do\" aria-label=\"subemnu\">지점별 평점</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li><a href=\"#\">창업지원</a>\r\n");
      out.write("      <ul id=\"sub-menu\">\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/adminLaunchApproval.do\" aria-label=\"subemnu\">창업신청 승인</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 비대면강좌 서비스 -->\r\n");
      out.write("    \r\n");
      out.write("    <li><a href=\"\">창업지원 교육자료</a>\r\n");
      out.write("      <ul id=\"sub-menu\">\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Study/studyflist\" aria-label=\"subemnu\">더원 교육자료</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Study/list\" aria-label=\"subemnu\">신메뉴 교육자료</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li><a href=\"#\">재고관리</a>\r\n");
      out.write("      <ul id=\"sub-menu\">\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/selectorder/from/franchise\" aria-label=\"subemnu\">주문현황</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/addmenu\" aria-label=\"subemnu\">메뉴 추가구성</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("        <li><a href=\"#\" aria-label=\"subemnu\">submenu</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li><a href=\"#\">MENU5</a></li>\r\n");
      out.write("    <li><a href=\"#\">MENU6</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"sub_section menu_wrap\" style=\"width:100%\";>\r\n");
      out.write("\t<div class=\"container\" style=\"margin-left:200px; margin-top:60px; height: 500px\">\r\n");
      out.write("\t\t<div style=\"width:600px; height: 500px; float: left\">\r\n");
      out.write("\t\t    <canvas id=\"myChart\"></canvas>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("// 우선 컨텍스트를 가져옵니다. \r\n");
      out.write("var ctx = document.getElementById(\"myChart\").getContext('2d');\r\n");
      out.write("/*\r\n");
      out.write("- Chart를 생성하면서, \r\n");
      out.write("- ctx를 첫번째 argument로 넘겨주고, \r\n");
      out.write("- 두번째 argument로 그림을 그릴때 필요한 요소들을 모두 넘겨줍니다. \r\n");
      out.write("*/\r\n");
      out.write("var myChart = new Chart(ctx, {\r\n");
      out.write("    type: 'bar',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: [\"더원\", \"한신포차\", \"백다방\"],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("            label: '더원의 매출현황',\r\n");
      out.write("            data: [");
      out.print(theoneprice);
      out.write(',');
      out.write(' ');
      out.print(hanshinprice);
      out.write(',');
      out.write(' ');
      out.print(paiksprice);
      out.write("],\r\n");
      out.write("            backgroundColor: [\r\n");
      out.write("                'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("                'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                'rgba(255, 206, 86, 0.2)'\r\n");
      out.write("                            ],\r\n");
      out.write("            borderColor: [\r\n");
      out.write("                'rgba(255,99,132,1)',\r\n");
      out.write("                'rgba(54, 162, 235, 1)',\r\n");
      out.write("                'rgba(255, 159, 64, 1)'\r\n");
      out.write("            ],\r\n");
      out.write("            borderWidth: 1\r\n");
      out.write("        }]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("        maintainAspectRatio: false, // default value. false일 경우 포함된 div의 크기에 맞춰서 그려짐.\r\n");
      out.write("        scales: {\r\n");
      out.write("            yAxes: [{\r\n");
      out.write("                ticks: {\r\n");
      out.write("                    beginAtZero:true\r\n");
      out.write("                }\r\n");
      out.write("            }]\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<div style=\"height: 500px; text-align: center; margin-right: 200px;\">\r\n");
      out.write("\t\t\t<h2> 더원의 본사평가</h2><br/>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">더원의 매출현황 : ");
      out.print(df.format(theoneprice));
      out.write("</h3>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">한신포차의 매출현황 : ");
      out.print(df.format(hanshinprice) );
      out.write("</h3>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">백다방의 매출현황 : ");
      out.print(df.format(paiksprice) );
      out.write("</h3><br/>\r\n");
      out.write("\t\t\t<h3 style=\"border-bottom: 0px;\">※개선방안※<br/><br/>\r\n");
      out.write("\t\t\t");
if(5>0){
				
      out.write("맛에 조금더 신경써주세요!!<br/><br/>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</h3>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<div class=\"boardList\" style=\"margin-top: 20px; margin-left: 50px;\">\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/headquarter/searchdate.do\"> ");
      out.write("\r\n");
      out.write("               <p>기&nbsp;&nbsp;간 : &nbsp;\r\n");
      out.write("                  <input type=\"text\" id=\"datepicker1\" name=\"fromdate\"/>\r\n");
      out.write("               에서             \r\n");
      out.write("                  <input type=\"text\" id=\"datepicker2\" name=\"todate\"/>\r\n");
      out.write("                  <input type=\"submit\" id=\"btn\" value=\"조&nbsp;회\"/>\r\n");
      out.write("               </p>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
